[build]
builder = "nixpacks"
buildCommand = "python3.11 -m pip install --upgrade pip setuptools wheel && python3.11 -m pip install -r requirements.txt"

[deploy]
startCommand = "python3.11 -m gunicorn app:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "gcc", "binutils"]

[env]
PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_VERSION = "3.11"
PIP_PREFER_BINARY = "1"
