[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python3.11 -m gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.11.4"
PYTHONUNBUFFERED = "1"
DEBIAN_FRONTEND = "noninteractive"
LANG = "C.UTF-8"
LC_ALL = "C.UTF-8"
PORT = "8000"
