[build]
# Install dependencies as specified in requirements.txt
command = "pip install -r requirements.txt"

[deploy]
# Start your Flask application with Gunicorn,
# assuming your app is created in app.py and the Flask app object is named 'app'
command = "gunicorn --bind 0.0.0.0:$PORT app:app"

[env]
PYTHON_VERSION = "3.10" 