[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11.4"
PYTHONUNBUFFERED = "1"
DEBIAN_FRONTEND = "noninteractive"
LANG = "C.UTF-8"
LC_ALL = "C.UTF-8"
